// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nursoft.DAL;

namespace Nursoft.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nursoft.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Qualified Workers Lorem Ipsum is simply dummy text of the printi",
                            Name = "WE ARE FAST"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Repair on Demand Lorem Ipsum is simply dummy text of the printing",
                            Name = "NO FIX, NO FEE"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Guaranteed Service Lorem Ipsum is simply dummy text of the printing",
                            Name = "30 DAYS WARRANTY"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Available Anytime Lorem Ipsum is simply dummy text of the printing",
                            Name = "EXPERT STAFF"
                        });
                });

            modelBuilder.Entity("Nursoft.Models.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "starting at...",
                            Image = "notebook-dark.png",
                            Name = "Laptop Repair"
                        },
                        new
                        {
                            Id = 2,
                            Description = "starting at...",
                            Image = "computer-dark.png",
                            Name = "Computer Repair"
                        },
                        new
                        {
                            Id = 3,
                            Description = "starting at...",
                            Image = "printer-dark.png",
                            Name = "Printer Repair"
                        },
                        new
                        {
                            Id = 4,
                            Description = "starting at...",
                            Image = "mobile-dark.png",
                            Name = "Smartphone Repair"
                        });
                });

            modelBuilder.Entity("Nursoft.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-1.jpg",
                            Name = "Data backup &amp; recovery"
                        },
                        new
                        {
                            Id = 2,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-2.jpg",
                            Name = "Laptop &amp; Mac Upgrade"
                        },
                        new
                        {
                            Id = 3,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-3.jpg",
                            Name = "Data backup &amp; recovery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-4.jpg",
                            Name = "Data backup &amp; recovery"
                        },
                        new
                        {
                            Id = 5,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-5.jpg",
                            Name = "Data backup &amp; recovery"
                        },
                        new
                        {
                            Id = 6,
                            Description = "We working hard to build a reputation of customer satisfaction through technical excellence and friendly staff",
                            Image = "item-6.jpg",
                            Name = "Data backup &amp; recovery"
                        });
                });

            modelBuilder.Entity("Nursoft.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "motherboard-1.jpg",
                            Subtitle = "Just send valuable laptop, PC, MAC, Mobile,<br>Gaming Device or Smartphone and we'll take care of it.",
                            Title = "Fast & Quick Fix"
                        },
                        new
                        {
                            Id = 2,
                            Image = "motherboard-3.jpg",
                            Title = "Any Kind of Upgrades"
                        },
                        new
                        {
                            Id = 3,
                            Image = "data-recovery.jpg",
                            Subtitle = "You Lose - We'll Find",
                            Title = "Data Recovery"
                        });
                });

            modelBuilder.Entity("Nursoft.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thanks John, I was really pleased with Profix’s service. Would definitely recommend you and have alredy given out some of your business cards that were left with me. All the best for future succes.",
                            Image = "notebook-sm.png",
                            Name = "Michale John",
                            Position = "Co-Founder, InfoLabs"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Profix did great job with fixing my laptop for a good price. I recommend any body with laptop problems, they will give you excellent service to all his customers.",
                            Image = "computer-sm.png",
                            Name = "Merry Smith",
                            Position = "CFO, InfoTech"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Keep up the excellent work. Thank you so much for your help. This is simply unbelievable!",
                            Image = "mobile-sm.png",
                            Name = "Merry Doe",
                            Position = "CFO, InfoTech"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
